# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 134d30d05f1f496d0f0a75b8bf0cc2b229e41fd1772a643e2fe418cbb61ee33ab341ecbe325ed563093562428226588023a6f13d02b01d342f4532e629d1c275

test:
  secret_key_base: 3991b0313c38788d597fe77f696e46882fcb21b5abbcaad3f6844b055febcf05f4cb43dab6109157cc73b7f58edf1eee5dec3813936e9baae68d47acadf552f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
